{% set name = "opentelemetry-instrumentation-celery" %}
{% set version = "0.25b2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-celery-{{ version }}.tar.gz
  sha256: 498ff0742df88ceb2ed1e5714668fbe01988a8ab229fb26f1ceb4a675d7a63dd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.25b2
    - opentelemetry-semantic-conventions ==0.25b2
    - python >=3.6
    # - pytest 
    # - opentelemetry-test ==0.24b0
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test ==0.25b0
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test ==0.25b1
    # - celery <6.0,>=4.0
    # - pytest 
    # - opentelemetry-test ==0.25b2
    # - celery <6.0,>=4.0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-celery
  summary: OpenTelemetry Celery Instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
